apiVersion: v1
kind: Secret
metadata:
  name: pano-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MESHDB_API_URL: {{ .Values.meshdb.url | b64enc | quote }}
  MESHDB_API_TOKEN: {{ .Values.meshdb.token | b64enc | quote }}
